- name: Tag Play
  hosts: web
  become: yes
  tasks:
    - name: Update Cache
      tags: update
      apt:
        update_cache: yes
    - name: Installing Nginx
      tags: install
      apt:
        name: nginx
        state: latest
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
