- name: Variables Play
  hosts: web
  gather_facts: true
  become: yes
  vars:
    restart: true
  tasks:
    - name: install nginx depends on Debian distro
      apt:
        name:  nginx
        state: latest
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install apache depends on CentOS distro
      service:
        apt:  httpd
        state: latest
      when: ansible_facts['distribution'] == "CentOS" 

    - name: restart nginx depends on distro
      service:
        name:  nginx
        state: restarted
      when: ansible_facts['distribution'] == "Ubuntu" and '{{ restart }} == true'
     
